language: node_js
node_js:
  - "14.8.0"

cache:
  directories:
    - node_modules

script:
  - echo "skipping tests"
  # - npm run test
  # - npm run build

# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN
#   keep-history: true
#   on:
#     branch: master
#   local_dir: build

before_deploy:
  - npm run build

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true
    bucket: "dev.duocun.ca"
    region: us-east-1
    local_dir: www
    on:
      repo: duocun/duocun-mall
      branch: develop
